server:
  port: 4000

spring:
  name: ev_charge
  jpa:
    database: POSTGRESQL
   # show-sql: true
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1030216350


logging:
  level:
    org:
      hibernate:
          SQL: trace
          orm:
            jdbc:
              bind: trace
